
development:
  adapter: postgresql
  encoding: unicode
  database: realestate_app_development
  pool: 5
  username: Olly
  password: 

production:
    adapter: postgresql
    encoding: unicode
    database: realestate_app_production
    pool: 5
    password: 

